export const Languages = {
  en: require('@/locales/en/messages').messages,
  ro: require('@/locales/ro/messages').messages,
  hu: require('@/locales/hu/messages').messages,
  it: require('@/locales/it/messages').messages,
  de: require('@/locales/de/messages').messages,
  fr: require('@/locales/fr/messages').messages,
  es: require('@/locales/es/messages').messages,
  af: require('@/locales/af/messages').messages,
  sq: require('@/locales/sq/messages').messages,
  ar: require('@/locales/ar/messages').messages,
  az: require('@/locales/az/messages').messages,
  be: require('@/locales/be/messages').messages,
  bn: require('@/locales/bn/messages').messages,
  bs: require('@/locales/bs/messages').messages,
  bg: require('@/locales/bg/messages').messages,
  zh: require('@/locales/zh/messages').messages,
  co: require('@/locales/co/messages').messages,
  hr: require('@/locales/hr/messages').messages,
  cs: require('@/locales/cs/messages').messages,
  da: require('@/locales/da/messages').messages,
  nl: require('@/locales/nl/messages').messages,
  et: require('@/locales/et/messages').messages,
  fi: require('@/locales/fi/messages').messages,
  ka: require('@/locales/ka/messages').messages,
  el: require('@/locales/el/messages').messages,
  he: require('@/locales/he/messages').messages,
  hi: require('@/locales/hi/messages').messages,
  is: require('@/locales/is/messages').messages,
  id: require('@/locales/id/messages').messages,
  ga: require('@/locales/ga/messages').messages,
  ja: require('@/locales/ja/messages').messages,
  ko: require('@/locales/ko/messages').messages,
  la: require('@/locales/la/messages').messages,
  lt: require('@/locales/lt/messages').messages,
  mk: require('@/locales/mk/messages').messages,
  ms: require('@/locales/ms/messages').messages,
  mn: require('@/locales/mn/messages').messages,
  ne: require('@/locales/ne/messages').messages,
  no: require('@/locales/no/messages').messages,
  pl: require('@/locales/pl/messages').messages,
  pt: require('@/locales/pt/messages').messages,
  ru: require('@/locales/ru/messages').messages,
  sr: require('@/locales/sr/messages').messages,
  sl: require('@/locales/sl/messages').messages,
  sv: require('@/locales/sv/messages').messages,
  th: require('@/locales/th/messages').messages,
  tr: require('@/locales/tr/messages').messages,
  uk: require('@/locales/uk/messages').messages,
  vi: require('@/locales/vi/messages').messages
};

export const LanguagesList = [
  { code: 'en', english: 'English', native: 'English' },
  { code: 'ro', english: 'Romanian', native: 'Română' },
  { code: 'hu', english: 'Hungarian', native: 'Magyar' },
  { code: 'it', english: 'Italian', native: 'Italiano' },
  { code: 'de', english: 'German', native: 'Deutsch' },
  { code: 'fr', english: 'French', native: 'Français' },
  { code: 'es', english: 'Spanish', native: 'Español' },
  { code: 'af', english: 'Afrikaans', native: 'Afrikaans' },
  { code: 'sq', english: 'Albanian', native: 'Shqip' },
  { code: 'ar', english: 'Arabic', native: 'العربية' },
  { code: 'az', english: 'Azerbaijani', native: 'Azərbaycanca' },
  { code: 'be', english: 'Belarusian', native: 'Беларуская' },
  { code: 'bn', english: 'Bengali', native: 'বাংলা' },
  { code: 'bs', english: 'Bosnian', native: 'Bosanski' },
  { code: 'bg', english: 'Bulgarian', native: 'Български' },
  { code: 'zh', english: 'Chinese', native: '中文' },
  { code: 'co', english: 'Corsican', native: 'Corsu' },
  { code: 'hr', english: 'Croatian', native: 'Hrvatski' },
  { code: 'cs', english: 'Czech', native: 'Čeština' },
  { code: 'da', english: 'Danish', native: 'Dansk' },
  { code: 'nl', english: 'Dutch', native: 'Nederlands' },
  { code: 'et', english: 'Estonian', native: 'Eesti' },
  { code: 'fi', english: 'Finnish', native: 'Suomi' },
  { code: 'ka', english: 'Georgian', native: 'ქართული' },
  { code: 'el', english: 'Greek', native: 'Ελληνικά' },
  { code: 'he', english: 'Hebrew', native: 'עברית' },
  { code: 'hi', english: 'Hindi', native: 'हिन्दी' },
  { code: 'is', english: 'Icelandic', native: 'Íslenska' },
  { code: 'id', english: 'Indonesian', native: 'Bahasa Indonesia' },
  { code: 'ga', english: 'Irish', native: 'Gaeilge' },
  { code: 'ja', english: 'Japanese', native: '日本語' },
  { code: 'ko', english: 'Korean', native: '한국어' },
  { code: 'la', english: 'Latin', native: 'Latina' },
  { code: 'lt', english: 'Lithuanian', native: 'Lietuvių' },
  { code: 'mk', english: 'Macedonian', native: 'Македонски' },
  { code: 'ms', english: 'Malay', native: 'Bahasa Melayu' },
  { code: 'mn', english: 'Mongolian', native: 'Монгол' },
  { code: 'ne', english: 'Nepali', native: 'नेपाली' },
  { code: 'no', english: 'Norwegian', native: 'Norsk' },
  { code: 'pl', english: 'Polish', native: 'Polski' },
  { code: 'pt', english: 'Portuguese', native: 'Português' },
  { code: 'ru', english: 'Russian', native: 'Русский' },
  { code: 'sr', english: 'Serbian', native: 'Српски' },
  { code: 'sl', english: 'Slovenian', native: 'Slovenščina' },
  { code: 'sv', english: 'Swedish', native: 'Svenska' },
  { code: 'th', english: 'Thai', native: 'ไทย' },
  { code: 'tr', english: 'Turkish', native: 'Türkçe' },
  { code: 'uk', english: 'Ukrainian', native: 'Українська' },
  { code: 'vi', english: 'Vietnamese', native: 'Tiếng Việt' }
];
